APPLICATION_NAME = 'Warmuppy'
APPLICATION_VERSION = '0.2'

DEFAULT_BPM = 100
DEFAULT_CUT = 0.02
DEFAULT_STEP = 1
DEFAULT_EXERCISES = [
    ["Scale up/down, 2 steps", [0, 2, 4, 2, 0]],
    ["Octave up/down", [0, 12, 0]],
]
DEFAULT_EXERCISE = 0
DEFAULT_PREVIEW = True
DEFAULT_PREVIEW_TIME = 3
DEFAULT_PROLONG = True
DEFAULT_PROLONG_TIME = 3
DEFAULT_INSTRUMENT = 0

INSTRUMENTS = [
    "Acoustic Grand Piano",
    "Bright Acoustic Piano",
    "Electric Grand Piano",
    "Honky-Tonk Piano",
    "Rhodes Piano",
    "Chorused Piano",
    "Harpsichord",
    "Clavinet",
    "Celesta",
    "Glockenspiel",
    "Music Box",
    "Vibraphone",
    "Marimba",
    "Xylophone",
    "Tubular Bells",
    "Dulcimer",
    "Hammond Organ",
    "Percussive Organ",
    "Rock Organ",
    "Church Organ",
    "Reed Organ",
    "Accordion",
    "Harmonica",
    "Tango Accordion",
    "Acoustic Guitar - Nylon",
    "Acoustic Guitar - Steel",
    "Electric Guitar - Jazz",
    "Electric Guitar - Clean",
    "Electric Guitar - Muted",
    "Overdriven Guitar",
    "Distortion Guitar",
    "Guitar Harmonics",
    "Acoustic Bass",
    "Electric Bass - Finger",
    "Electric Bass - Pick",
    "Fretless Bass",
    "Slap Bass 1",
    "Slap Bass 2",
    "Synth Bass 1",
    "Synth Bass 2",
    "Violin",
    "Viola",
    "Cello",
    "Contrabass",
    "Tremolo Strings",
    "Pizzicato Strings",
    "Orchestral Harp",
    "Timpani",
    "String Ensemble 1",
    "String Ensemble 2",
    "Synth. Strings 1",
    "Synth. Strings 2",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Voice",
    "Orchestra Hit",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Muted Trumpet",
    "French Horn",
    "Brass Section",
    "Synth. Brass 1",
    "Synth. Brass 2",
    "Soprano Sax",
    "Alto Sax",
    "Tenor Sax",
    "Baritone Sax",
    "Oboe",
    "English Horn",
    "Bassoon",
    "Clarinet",
    "Piccolo",
    "Flute",
    "Recorder",
    "Pan Flute",
    "Bottle Blow",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Synth Lead 1 - Square",
    "Synth Lead 2 - Sawtooth",
    "Synth Lead 3 - Calliope",
    "Synth Lead 4 - Chiff",
    "Synth Lead 5 - Charang",
    "Synth Lead 6 - Voice",
    "Synth Lead 7 - Fifths",
    "Synth Lead 8 - Brass + Lead",
    "Synth Pad 1 - New Age",
    "Synth Pad 2 - Warm",
    "Synth Pad 3 - Polysynth",
    "Synth Pad 4 - Choir",
    "Synth Pad 5 - Bowed",
    "Synth Pad 6 - Metallic",
    "Synth Pad 7 - Halo",
    "Synth Pad 8 - Sweep"
]

NOTES = [
    "C",
    "Cs",
    "D",
    "Ds",
    "E",
    "F",
    "Fs",
    "G",
    "Gs",
    "A",
    "As",
    "B",
]
